apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: mydata
spec:
  hosts:
  - "mydata"
  http:
  - route:
      - destination:
          host: mydata
          subset: v1
        weight: 60
      - destination:
          host: mydata
          subset: v2
        weight: 20
      - destination:
          host: mydata
          subset: v3
        weight: 20